### ISSUE TITLE
keyboard jogging non  grblHAL

### ISSUE THREAD

**Issue by jschoch** [terjeio/Grbl-GCode-Sender#22]
saw this was disabled, wondering about the thinking behind it?

**Comment by terjeio** [comment]
Because grbl does not handle jog cancel correctly. It may miss probing commands in the pipeline (serial input buffer and block input buffer) and just continue moving. I do not like the suggested workaround for that, IMO it should be fixed but as I undertands it the maintainer does not want to do that.

**Comment by terjeio** [comment]
Setting to enable in _Settings: App_ added.
