### ISSUE TITLE
small shortcut issue

### ISSUE THREAD

**Issue by S2000Stefan** [terjeio/Grbl-GCode-Sender#69]
If you select either G28 or G30 in the Goto flyout tab and then try to reactivate jogging with Ctrl+Shift this is not possible. Closing the flyout tab does not help either.
If you enter G28 or G30 in the MDI the shortcut Ctrl+Shift works to activate jogging.

**Comment by terjeio** [comment]
Missed that detail, will be fixed in next build (clicking on the Goto... buttons took away focus from the tab). In the next build the buttons will be disabled until the machine is homed as well. Ref. LinuxCNC docs:

> Warning
Only use G28 when your machine is homed to a repeatable position and the desired G28 position has been stored with G28.1.
