### ISSUE TITLE
Finally found it but is there a windows installation package for it

### ISSUE THREAD

**Issue by MeJasonT** [terjeio/Grbl-GCode-Sender#72]
You mentioned a while ago you were writing a GUI, well done buddy it looks good and looks to include many of the functions missing from GRBL Panel.
As you have mentioned gerrit has discontinued Grbl-Panel now.
i spotted you had added many of the features i requested such as tool management and conversational.
The two things i noticed off the bat was no A axis and its a load of files that have to be built before installation.  many of us are used to point and click install under the windows enviroment so somthing along those lines would be greatfully appreciated.
Its certainly a very full and function rich application.

**Comment by terjeio** [comment]
> The two things i noticed off the bat was no A axis

AFAIKT the original grbl does not support more than 3 axes, [grblHAL](https://github.com/terjeio/grblHAL) does and report the number back in the [$I report](https://github.com/terjeio/grblHAL/wiki/Report-extensions#i-info-report-extensions). The sender uses this to automatically enable axes. Other grbl ports needs to have this extension added? grblHAL could be a better option since the sender unlocks even more features if detected.

>  its a load of files that have to be built before installation.

No installation package or build is needed, unzip a [prebuilt version](https://github.com/terjeio/Grbl-GCode-Sender/releases) to where you want it and run GCode Sender.exe. I have considered making an installer, perhaps I'll do that for the first production release.

> Its certainly a very full and function rich application.

Thanks, my aim is to provide a sender that can take full advantage of grblHAL features and at the same time be useful to legacy grbl users.
